on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          make build-ci

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: signals
          include-hidden-files: true
          path: ./bin/