on:
  push:
    tags:
    - 'v*'

name: Release

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: |
          make build-ci
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/signals-windows-amd64.exe
            bin/signals-linux-amd64
            bin/signals-linux-arm64
            bin/signals-darwin-arm64
            bin/.env.local
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}